version: "1.1"

services:
  backend:
    build: .
    container_name: kriyado-backend
    volumes:
      - ./:/backend
    command: >
      sh -c "python manage.py migrate --noinput && 
      uvicorn kriyado.asgi:application --host 0.0.0.0 --port 8000 --workers ${UVICORN_WORKERS:-4}"
    ports:
      - "8000:8000"
    env_file: .env
    restart: on-failure
