version: "1.1"

services:
  postgres:
    image: postgres:16
    container_name: kriyado-postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U "]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  backend:
    build: .
    container_name: kriyado-backend
    volumes:
      - ./:/backend
    command: >
      python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file: .env
    restart: on-failure

volumes:
  postgres_data:
