# Generated by Django 5.2.6 on 2025-10-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
